# Generated by Django 5.0.7 on 2024-07-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('title', models.CharField(max_length=70)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
