# Generated by Django 5.0.7 on 2024-07-29 23:15

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', django_quill.fields.QuillField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('is_draft', models.BooleanField(blank=True, default=False)),
                ('tags', models.ManyToManyField(to='blog.tag')),
            ],
        ),
    ]
